//
//  NamesListPresenterTests.swift
//  GitHubMessenger
//
//  Created by Gabriel Targon on 30/04/21.
//  Copyright (c) 2021 Gabriel Targon. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import GitHubMessenger
import XCTest

class NamesListPresenterTests: XCTestCase {
    // MARK: Subject under test
    
    private var sut: NamesListPresenter!
    private var viewControllerSpy: NamesListViewControllerSpy!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        viewControllerSpy = NamesListViewControllerSpy()
        sut = NamesListPresenter(viewController: viewControllerSpy)
    }
    
    override func tearDown() {
        sut = nil
        viewControllerSpy = nil
        super.tearDown()
    }
    
    // MARK: Tests
    
    func testPresentChat() {
        sut.presentChat()
        XCTAssertTrue(viewControllerSpy.displayChatCalled)
    }
    
    func testPresentUserList() {
        sut.presentUserList(response: NamesListSeeds.UserListArray)
        XCTAssertTrue(viewControllerSpy.displayUserListCalled)
    }
}
