//
//  NamesListViewControllerTests.swift
//  GitHubMessenger
//
//  Created by Gabriel Targon on 30/04/21.
//  Copyright (c) 2021 Gabriel Targon. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import GitHubMessenger
import XCTest

class NamesListViewControllerTests: XCTestCase {
    // MARK: Subject under test
    
    var sut: NamesListViewController!
    private var interactorSpy: NamesListInteractorSpy!
    private var routerSpy: NamesListRouterSpy!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        sut = NamesListViewController()
        interactorSpy = NamesListInteractorSpy()
        routerSpy = NamesListRouterSpy()
        setupNamesListViewController()
        sut.setup(interactor: interactorSpy, router: routerSpy)
    }
    
    override func tearDown() {
        sut = nil
        interactorSpy = nil
        routerSpy = nil
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupNamesListViewController() {
        let bundle = Bundle.main
        let storyboard = UIStoryboard(name: "NamesList", bundle: bundle)
        sut = storyboard.instantiateViewController(withIdentifier: "NamesListViewController") as? NamesListViewController
        sut.loadViewIfNeeded()
    }
    
    // MARK: Tests
    
    func testDisplayChat() {
        sut.displayChat()
        XCTAssertTrue(routerSpy.routeToChatCalled)
    }
    
    func testDisplaySomething() {
        sut.displayUserList(viewModel: NamesListSeeds.UserListArray)
        XCTAssertEqual(sut.userList.count, 4)
    }
}
