//
//  NamesListInteractorTests.swift
//  GitHubMessenger
//
//  Created by Gabriel Targon on 30/04/21.
//  Copyright (c) 2021 Gabriel Targon. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import GitHubMessenger
import XCTest

class NamesListInteractorTests: XCTestCase {
    // MARK: Subject under test
    
    private var sut: NamesListInteractor!
    private var presenterSpy: NamesListPresenterSpy!
    private var workerSpy: NamesListWorkerSpy!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        presenterSpy = NamesListPresenterSpy()
        workerSpy = NamesListWorkerSpy()
        sut = NamesListInteractor(presenter: presenterSpy, worker: workerSpy)
    }
    
    override func tearDown() {
        sut = nil
        presenterSpy = nil
        workerSpy = nil
        super.tearDown()
    }
    
    // MARK: Tests
    
    func testHandleNameTouched() {
        sut.handleNameTouched(request: NamesList.Name.Request(user: NamesListSeeds.User))
        XCTAssertNotNil(sut.user)
        XCTAssertEqual(sut.user.login, NamesListSeeds.User.login)
        XCTAssertTrue(presenterSpy.presentChatCalled)
    }
    
    func testHandleGetUserInfo() {
        sut.handleGetUserInfo()
        XCTAssertTrue(workerSpy.requestGitHubUserInfoCalled)
    }
}
