//
//  ChatPresenterTests.swift
//  GitHubMessenger
//
//  Created by Gabriel Targon on 30/04/21.
//  Copyright (c) 2021 Gabriel Targon. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import XCTest
@testable import GitHubMessenger

final class ChatPresenterTests: XCTestCase {
    // MARK: Subject under test
    private var sut: ChatPresenter!
    private var viewControllerSpy: ChatViewControllerSpy!
    
    // MARK: Test lifecycle
    override func setUp() {
        super.setUp()
        viewControllerSpy = ChatViewControllerSpy()
        sut = ChatPresenter(viewController: viewControllerSpy)
    }
    
    override func tearDown() {
        viewControllerSpy = nil
        super.tearDown()
    }
}
