//
//  ChatViewControllerTests.swift
//  GitHubMessenger
//
//  Created by Gabriel Targon on 30/04/21.
//  Copyright (c) 2021 Gabriel Targon. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import XCTest
@testable import GitHubMessenger

final class ChatViewControllerTests: XCTestCase {
    // MARK: Subject under test
    private var sut: ChatViewController!
    private var interactorSpy: ChatInteractorSpy!
    private var routerSpy: ChatRouterSpy!
    
    // MARK: Test lifecycle
    override func setUp() {
        super.setUp()
        sut = ChatViewController()
        interactorSpy = ChatInteractorSpy()
        routerSpy = ChatRouterSpy()
        sut.setup(interactor: interactorSpy, router: routerSpy)
    }
    
    override func tearDown() {
        interactorSpy = nil
        routerSpy = nil
        sut = nil
        super.tearDown()
    }
    
    // MARK: Tests
    func testGetInfos() {
        sut.getInfos()
        XCTAssertEqual(sut.user, "Teste")
    }
    
    func testSendMessage() {
        sut.messages = interactorSpy.getMessages()
        sut.sendMessage()
        XCTAssert(interactorSpy.saveMessageCalled)
    }
}
