//
//  ChatInteractorSpy.swift
//  GitHubMessenger
//
//  Created by Gabriel Targon on 30/04/21.
//  Copyright (c) 2021 Gabriel Targon. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import GitHubMessenger
import CoreData
import XCTest

final class ChatInteractorSpy: XCTestCase, ChatDataStore {
    var user: NamesList.User?
    
    var returnUserLoginCalled = false
    var getMessagesCalled = false
    var saveMessageCalled = false
}

extension ChatInteractorSpy: ChatBusinessLogic {
    func returnUserLogin() -> String {
        returnUserLoginCalled = true
        return ChatSeeds.ChatUser
    }
    
    func getMessages() -> [NSManagedObject] {
        getMessagesCalled = true
        
        var messages: [NSManagedObject] = []
        
        guard let appDelegate = UIApplication.shared.delegate as? AppDelegate else {
            return [NSManagedObject]()
        }
        
        let managedContext = appDelegate.persistentContainer.viewContext
        let fetchRequest = NSFetchRequest<NSManagedObject>(entityName: "Message")
        
        do {
            messages = try managedContext.fetch(fetchRequest)
            return messages
        } catch let error as NSError {
            print("Error to load CoreData: \(error)")
            return [NSManagedObject]()
        }
    }
    
    func saveMessage(request: Chat.Message.Request) {
        saveMessageCalled = true
    }
}
