//
//  ChatWorkerSpy.swift
//  GitHubMessenger
//
//  Created by Gabriel Targon on 30/04/21.
//  Copyright (c) 2021 Gabriel Targon. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import GitHubMessenger
import CoreData

final class ChatWorkerSpy {
    var saveMessageCalled = false
    var getMessagesCalled = false
}

extension ChatWorkerSpy: ChatWorkLogic {
    func saveMessage(msg: Chat.Message.Request) {
        saveMessageCalled = true
    }
    
    func getMessages() -> [NSManagedObject] {
        getMessagesCalled = true
        return []
    }
}
