//
//  ChatRouter.swift
//  GitHubMessenger
//
//  Created by Gabriel Targon on 12/03/20.
//  Copyright (c) 2020 Gabriel Targon. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ChatRoutingLogic {}

protocol ChatDataPassing {
    var dataStore: ChatDataStore? { get }
}

class ChatRouter: ChatDataPassing, ChatRoutingLogic {
    private weak var viewController: UIViewController?
    var dataStore: ChatDataStore?
    
    init(viewController: UIViewController, dataStore: ChatDataStore?) {
        self.viewController = viewController
        self.dataStore = dataStore
    }
}
