//
//  ChatPresenter.swift
//  GitHubMessenger
//
//  Created by Gabriel Targon on 12/03/20.
//  Copyright (c) 2020 Gabriel Targon. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChatPresentationLogic {}

class ChatPresenter {
    private weak var viewController: ChatDisplayLogic?
    
    init(viewController: ChatDisplayLogic) {
        self.viewController = viewController
    }
}

extension ChatPresenter: ChatPresentationLogic {}
