//
//  ChatModels.swift
//  GitHubMessenger
//
//  Created by Gabriel Targon on 12/03/20.
//  Copyright (c) 2020 Gabriel Targon. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import CoreData

enum Chat {
    enum Message {
        struct Request {
            let text: String
            let type: ChatType
            let date: Date
            let friend: String
        }
        
        struct Response {
            let messages: [NSManagedObject]
        }
        
        struct ViewModel {
            let messages: [NSManagedObject]
        }
    }
}

enum ChatType: String {
    case incoming = "incoming"
    case outgoing = "outgoing"
}
