//
//  ChatInteractor.swift
//  GitHubMessenger
//
//  Created by Gabriel Targon on 12/03/20.
//  Copyright (c) 2020 Gabriel Targon. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChatBusinessLogic {
    func saveMessage(request: Chat.Message.Request)
}

protocol ChatDataStore {
    //var name: String { get set }
}

class ChatInteractor: ChatBusinessLogic, ChatDataStore {
    var presenter: ChatPresentationLogic?
    var worker: ChatWorker?
    
    init(presenter: ChatPresentationLogic,
         worker: ChatWorker) {
        self.presenter = presenter
        self.worker = worker
    }
    
    func saveMessage(request: Chat.Message.Request) {
        worker?.saveMessage(msg: request)
    }
}
