//
//  NamesListModels.swift
//  GitHubMessenger
//
//  Created by Gabriel Targon on 12/03/20.
//  Copyright (c) 2020 Gabriel Targon. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Foundation

enum NamesList {
    // MARK: Use cases
    
    enum Name {
        struct Request {
            let user: User
        }
        struct Response {
            let user: User
        }
        struct ViewModel {
            let user: User
        }
    }
    
    struct User: Codable {
        let login: String
        let id: Int
        let avatarUrl: String
        
        enum CodingKeys: String, CodingKey {
            case login
            case id
            case avatarUrl = "avatar_url"
        }
        
        init(login: String,
             id: Int,
             avatar: String) {
            self.login = login
            self.id = id
            self.avatarUrl = avatar
        }
    }
}




