//
//  NamesListRouter.swift
//  GitHubMessenger
//
//  Created by Gabriel Targon on 12/03/20.
//  Copyright (c) 2020 Gabriel Targon. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NamesListRoutingLogic {
    func routeToChat()
}

protocol NamesListDataPassing {
    var dataStore: NamesListDataStore? { get }
}

class NamesListRouter: NamesListDataPassing {
    private weak var viewController: UIViewController?
    var dataStore: NamesListDataStore?
    
    init(viewController: UIViewController, dataStore: NamesListDataStore?) {
        self.viewController = viewController
        self.dataStore = dataStore
    }
}

extension NamesListRouter: NamesListRoutingLogic {
    func routeToChat() {
        let vc = ChatFactory.setupChat()
        var destinationDataStore = (vc as? ChatViewController)?.router?.dataStore
        passDataToChat(source: dataStore, destination: &destinationDataStore)
        viewController?.navigationController?.pushViewController(vc, animated: true)
    }
}

extension NamesListRouter {
    func passDataToChat(source: NamesListDataStore?, destination: inout ChatDataStore?) {
        guard let user = source?.user else { return }
        destination?.user = user
    }
}
