//
//  NamesListInteractor.swift
//  GitHubMessenger
//
//  Created by Gabriel Targon on 12/03/20.
//  Copyright (c) 2020 Gabriel Targon. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NamesListBusinessLogic {
    func handleNameTouched(request: NamesList.Name.Request)
    func handleGetUserInfo()
}

protocol NamesListDataStore {
    var user: NamesList.User { get set }
}

class NamesListInteractor: NamesListBusinessLogic, NamesListDataStore {
    
    var presenter: NamesListPresentationLogic?
    var worker: NamesListWorkLogic?
    
    var user = NamesList.User(login: String(), id: Int(), avatar: String())
    
    init(presenter: NamesListPresentationLogic,
         worker: NamesListWorkLogic) {
        self.presenter = presenter
        self.worker = worker
    }
    
    func handleNameTouched(request: NamesList.Name.Request) {
        user = request.user
        presenter?.presentChat()
    }
    
    func handleGetUserInfo() {
        worker?.requestGitHubUserInfo { (users) in
            self.presenter?.presentUserList(response: users ?? [])
        }
    }
}
