//
//  ChatModels.swift
//  GitHubMessenger
//
//  Created by Gabriel Targon on 12/03/20.
//  Copyright (c) 2020 Gabriel Targon. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class Friend: NSObject {
    var name: String?
    var profileImageName: String?
}

class Message: NSObject {
    var text: String?
    var date: NSDate?
    var type: MessageType?
    var friend: Friend?
}

enum MessageType {
    case incoming
    case outgoing
}

enum Chat
{
    // MARK: Use cases
    
    enum Something
    {
        struct Request
        {
        }
        struct Response
        {
        }
        struct ViewModel
        {
        }
    }
}
