//
//  ChatInteractor.swift
//  GitHubMessenger
//
//  Created by Gabriel Targon on 12/03/20.
//  Copyright (c) 2020 Gabriel Targon. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChatBusinessLogic {
  func doSomething(request: Chat.Something.Request)
}

class ChatInteractor: ChatBusinessLogic, ChatDataStore {
  var presenter: ChatPresentationLogic?
  var worker: ChatWorker?
  
  // MARK: Do something
  
  func doSomething(request: Chat.Something.Request) {
    worker = ChatWorker()
    worker?.doSomeWork()
    
    let response = Chat.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
