//
//  ChatViewController.swift
//  GitHubMessenger
//
//  Created by Gabriel Targon on 12/03/20.
//  Copyright (c) 2020 Gabriel Targon. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChatDisplayLogic: class {
//    func displaySomething(viewModel: Chat.Something.ViewModel)
}

class ChatViewController: UIViewController, ChatDisplayLogic {
    //Architecture variables
    var interactor: ChatBusinessLogic?
    var router: (NSObjectProtocol & ChatRoutingLogic & ChatDataPassing)?
    
    //IBOutlets
    @IBOutlet weak var tableView: UITableView!
    @IBOutlet weak var sendMessageView: UIView!
    @IBOutlet weak var sendMessageTextField: UITextField!
    @IBOutlet weak var sendMessageButton: UIButton!
    
    //Constraints
    @IBOutlet weak var sendMessageViewHeightConstraint: NSLayoutConstraint!
    @IBOutlet weak var sendMessageViewBottomConstraint: NSLayoutConstraint!
    
    //Variables
    var user: NamesList.User?
    private var messages: [Message]? = []
    private let sendMessageViewHeight: CGFloat = 60
    private let sendMessageViewHeightIphoneXAndLater: CGFloat = 94
    private let sendMessageViewWidth: CGFloat = UIScreen.main.bounds.width
    private var isKeyboardVisible: Bool = false
    private var willDismissKeyboard: Bool = false
    private var keyboardSize: CGRect = CGRect.init(x: 0, y: 0, width: 0, height: 0)
    
    // MARK: Object lifecycle
    
    class func instantiateNew() -> ChatViewController {
        guard let viewController = UIStoryboard(name: "Chat", bundle: nil).instantiateViewController(withIdentifier: String(describing: self)) as? ChatViewController
            else { fatalError("Couldn't instantiate \(String(describing: self))") }
        return viewController
    }
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup() {
        let viewController = self
        let interactor = ChatInteractor()
        let presenter = ChatPresenter()
        let router = ChatRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        setupView()
        setupTableView()
        setSendMessageViewFrame()
    }
    
    func setupView() {
        title = user?.login
        sendMessageButton.isEnabled = false
        sendMessageTextField.addTarget(self, action: #selector(editingChanged), for: .editingChanged)
        
        NotificationCenter.default.addObserver(self, selector: #selector(keyboardWillShow(_:)), name: UIResponder.keyboardWillShowNotification, object: nil)
        NotificationCenter.default.addObserver(self, selector: #selector(keyboardDidShow(_:)), name: UIResponder.keyboardDidShowNotification, object: nil)
        NotificationCenter.default.addObserver(self, selector: #selector(keyboardWillHide(_:)), name: UIResponder.keyboardWillHideNotification, object: nil)
        NotificationCenter.default.addObserver(self, selector: #selector(keyboardDidHide(_:)), name: UIResponder.keyboardDidHideNotification, object: nil)
    }
    
    override func viewDidLayoutSubviews() {
        tableView.rowHeight = UITableView.automaticDimension
        tableView.estimatedRowHeight = 44
    }
    
    private func setupTableView() {
        self.tableView.dataSource = self
        self.tableView.delegate = self
        
        let nibIncoming = UINib(nibName: "ChatIncomingTableViewCell", bundle: nil)
        self.tableView.register(nibIncoming, forCellReuseIdentifier: "incomingMessageCell")
        
        let nibOutgoing = UINib(nibName: "ChatOutgoingTableViewCell", bundle: nil)
        self.tableView.register(nibOutgoing, forCellReuseIdentifier: "outgoingMessageCell")
    }
    
    private func setSendMessageViewFrame() {
        if let content = self.sendMessageView {
            if UIDevice.current.screenType == .iPhonesX {
                content.frame = CGRect.init(x: 0, y: (UIScreen.main.bounds.height - sendMessageViewHeightIphoneXAndLater), width: sendMessageViewWidth, height: sendMessageViewHeightIphoneXAndLater)
                sendMessageViewHeightConstraint.constant = sendMessageViewHeightIphoneXAndLater
            } else {
                content.frame = CGRect.init(x: 0, y: (UIScreen.main.bounds.height - sendMessageViewHeight), width: sendMessageViewWidth, height: sendMessageViewHeight)
                sendMessageViewHeightConstraint.constant = sendMessageViewHeight
            }
        }
    }
    
    // MARK: Functions
    
    private func sendOutgoingMessage(_ message: String) {
        let outgoingMsg = Message()
        outgoingMsg.text = "\(message) \(message)"
        outgoingMsg.type = .outgoing
        outgoingMsg.date = NSDate()
        
        messages?.append(outgoingMsg)
        
        tableView.reloadData()
    }
    
    @objc func editingChanged(sender: UITextField) {
        guard let name = sendMessageTextField.text, !name.isEmpty else {
            sendMessageButton.isEnabled = false
            return
        }
        
        sendMessageButton.isEnabled = true
        
    }
    
    private func scrollToBottom() {
        let point = CGPoint(x: 0, y: tableView.contentSize.height + tableView.contentInset.bottom - tableView.frame.height)
        if point.y >= 0{
            tableView.setContentOffset(point, animated: true)
        }
        tableView.layoutIfNeeded()
    }
    
    // MARK: Keyboard behaviour

    @objc func keyboardDidShow(_ notification: NSNotification) {
        isKeyboardVisible = true
        guard let info = notification.userInfo else{
            return
        }
        let keyboardFrame: CGRect = (info[UIResponder.keyboardFrameEndUserInfoKey] as! NSValue).cgRectValue
        keyboardSize = keyboardFrame
    }

    @objc func keyboardWillShow(_ notification: NSNotification) {
        if let info = notification.userInfo {
            let keyboardFrame: CGRect = (info[UIResponder.keyboardFrameEndUserInfoKey] as! NSValue).cgRectValue
            sendMessageViewHeightConstraint.constant = sendMessageViewHeight
            sendMessageViewBottomConstraint.constant = keyboardFrame.height
            scrollToBottom()
        }
    }

    @objc func keyboardDidHide(_ notification: NSNotification) {
        isKeyboardVisible = false
        willDismissKeyboard = false
        keyboardSize = CGRect.init(x: 0, y: 0, width: 0, height: 0)
        setSendMessageViewFrame()
    }

    @objc func keyboardWillHide(_ notification: NSNotification) {
        sendMessageViewBottomConstraint.constant = 0
    }
    
    // MARK: Actions
    
    @IBAction func sendMessage(_ sender: Any) {
        if let text = sendMessageTextField.text {
            let incomingMsg = Message()
            incomingMsg.text = text
            incomingMsg.date = NSDate()
            incomingMsg.type = .incoming
            messages?.append(incomingMsg)
            
            sendOutgoingMessage(text)
            
            sendMessageTextField.text = nil
            sendMessageButton.isEnabled = false
            scrollToBottom()
        }
    }
    
    
}

extension ChatViewController: UITableViewDelegate, UITableViewDataSource {
    // MARK: TableView Functions
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        if let count = messages?.count {
            return count
        }
        return 0
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        if let typeMsg = messages?[indexPath.row].type {
            if typeMsg == .incoming {
                let incomingCell = tableView.dequeueReusableCell(withIdentifier: "incomingMessageCell") as! ChatIncomingTableViewCell
                return incomingCell
            } else if typeMsg == .outgoing {
                let outgoingCell = tableView.dequeueReusableCell(withIdentifier: "outgoingMessageCell") as! ChatOutgoingTableViewCell
                return outgoingCell
            }
        }
        return UITableViewCell()
    }
    
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        
        if let messageText = messages?[indexPath.row].text {
            let size = CGSize(width: 250, height: 100)
            let options = NSStringDrawingOptions.usesFontLeading.union(.usesLineFragmentOrigin)
            let estimatedFrame = NSString(string: messageText).boundingRect(with: size, options: options, attributes: [NSAttributedString.Key.font : UIFont.systemFont(ofSize: 16)], context: nil)
            return estimatedFrame.height + 25
        }
        return 44
    }
    
    func tableView(_ tableView: UITableView, willDisplay cell: UITableViewCell, forRowAt indexPath: IndexPath) {
        guard let text = messages?[indexPath.row].text else {
            return
        }
        
        if let incomingCell = cell as? ChatIncomingTableViewCell {
            incomingCell.setLabelSize(messageText: text)
        } else if let outgoingCell = cell as? ChatOutgoingTableViewCell {
            outgoingCell.setLabelSize(messageText: text)
        }
    }
    
}
