//
//  ChatPresenter.swift
//  GitHubMessenger
//
//  Created by Gabriel Targon on 12/03/20.
//  Copyright (c) 2020 Gabriel Targon. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChatPresentationLogic {
  func presentSomething(response: Chat.Something.Response)
}

class ChatPresenter: ChatPresentationLogic {
  weak var viewController: ChatDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Chat.Something.Response) {
    let viewModel = Chat.Something.ViewModel()
//    viewController?.displaySomething(viewModel: viewModel)
  }
}
